### ISSUE TITLE
startGoldRainClick() not working any more

### ISSUE THREAD

**Issue by LMariachi** [mouseas/steamSummerMinigame#104]
As of this morning it seems that startGoldRainClick() is no longer triggering.

EDIT: It's triggering sporadically but I can't tell why.

**Comment by mouseas** [comment]
I just fixed it ~~25~~ 9 minutes ago, should be working now.

EDIT: forgot the version number bump for GM/TM

**Comment by LMariachi** [comment]
Update: Seems like it works until this error shows up in console:

`Failed to load resource: the server responded with a status of 503 (Service Unavailable)`

`XMLHttpRequest cannot load https://steamapi-a.akamaihd.net/ITowerAttackMiniGameService/UseAbilities/v0001/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://steamcommunity.com' is therefore not allowed access. The response had HTTP status code 503.`

And then no more gold rain click until reloading.

**Comment by mouseas** [comment]
@LMariachi have you tried the latest version, as of 9 minutes ago (or 33 minutes if using manual install)?

**Comment by LMariachi** [comment]
Yes, I'm up to date. It's still failing after some time, although that error hasn't shown up again.

**Comment by LMariachi** [comment]
Relaunched broswer instead of just closing/resuming game and now it seems fine. **shrug**

Thanks!
